# Lychee configuration for portfolio repositories
exclude = [
  "mailto:",
  "tel:",
  "https://img.shields.io"
]

accept = ["200", "206", "429"]
max_concurrency = 8
timeout = 20
insecure = false

exclude_path = [
  "submissions"
]
