name: "Quality Gate"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-and-spell:
    name: "Linting and Spell Check"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Markdown Lint"
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

      - name: "Spell Check"
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: "cspell.json"
          strict: true
          incremental_files_only: false
